### ISSUE TITLE
Connection refused - connect(2) for "localhost" port 25

### ISSUE THREAD

**Issue by ClemLC** [mailjet/mailjet-gem#137]
Hi !

I'm trying Mailjet for the very first time with a Rails app. (gem mailjet 1.5.4)

It's an online store, each time a customer make an order, an email is sent to him and to the admin of the website.

I'm testing it locally (development environment), and when i make an order i get this error message 

Errno::ECONNREFUSED in OrdersController#createorder
Connection refused - connect(2) for "localhost" port 25

    code...
    UserMailer.welcome_email(@user).deliver_now!
    code...

Can someone help me to solve this problem ?

**Comment by Lorel** [comment]
Hi @ClemLC 

You are trying to connect to `localhost`, instead of Mailjet, to send your emails
It looks like you didn't set properly your ActionMailer delivery method
Have a look to https://github.com/mailjet/mailjet-gem#send-emails-with-actionmailer
Don't forget to configure your Mailjet credentials also: https://github.com/mailjet/mailjet-gem#api-key
